# Generated by Django 2.2.3 on 2019-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True)),
                ('month', models.IntegerField(blank=True)),
                ('day', models.IntegerField()),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'food_menu',
            },
        ),
    ]
